"use client";
import Link from "next/link";
import {Bar,BarChart,CartesianGrid,Cell,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {bankDashboardAccounts} from "@/lib/bank-dashboard";
import {ledgerAmount,ledgerExpenseGroups,type LedgerEntry} from "@/lib/finance-ledger";
import {bankDate,bankMoney,bankResourceName} from "@/lib/open-finance-display";
import type {BankFinancialData} from "@/lib/open-finance-report";
import OpenFinanceIcon from "./OpenFinanceIcon";
const colors=["#7c3aed","#0ea5e9","#10b981","#f59e0b"];
export default function BankDashboard({data,entries}:{data:BankFinancialData;entries:LedgerEntry[]}){
  if(!data.overview.connections.length)return null;
  const groups=bankDashboardAccounts(data.overview),overview=data.overview;
  const expenses=ledgerExpenseGroups(entries,"origin");
  const cards=overview.resources.filter(r=>r.resource_type==="card");
  return <section aria-label="Visão das contas e cartões" className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-violet-700">Seus bancos na Zelo</p><h2 className="mt-1 text-xl font-bold tracking-tight text-slate-950">Uma visão completa do seu dinheiro</h2><p className="mt-1 text-xs text-slate-500">Saldo e limites são a posição recebida do banco. Os gastos acompanham o período selecionado.</p></div><Link href="/dashboard/contas" className="rounded-xl border border-violet-100 bg-violet-50 px-4 py-2 text-xs font-semibold text-violet-700">Gerenciar conexões →</Link></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <article className="min-w-0 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-violet-50 p-3 text-violet-600"><OpenFinanceIcon name="bank"/></span><div><h3 className="font-semibold text-slate-900">Saldo disponível por conta</h3><p className="mt-1 text-[11px] text-slate-500">Dinheiro nas contas · limite de cartão não entra aqui</p></div></div>
        {!groups.length&&<p className="py-12 text-center text-sm text-slate-400">O banco ainda não enviou contas.</p>}
        {groups.map(group=><div key={group.currency} className="mb-5 last:mb-0"><div className="mb-3 flex items-end justify-between"><p className="text-2xl font-bold tracking-tight text-slate-900">{group.currency==="Não informada"?"Moeda não informada":bankMoney(group.total,group.currency)}</p><span className="text-xs text-slate-400">{group.accounts.length} conta(s) · {group.currency}</span></div>
          {group.accounts.some(a=>a.amount!==null)&&<div role="img" aria-label={`Comparação dos saldos das contas em ${group.currency}`}><ResponsiveContainer width="100%" height={Math.min(300,Math.max(130,group.accounts.length*45))}><BarChart data={group.accounts.filter(a=>a.amount!==null)} layout="vertical" margin={{left:0,right:15,bottom:0,top:5}}><CartesianGrid stroke="#f1f5f9" horizontal={false}/><XAxis type="number" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis dataKey="name" type="category" width={110} tick={{fontSize:10}} axisLine={false} tickLine={false}/><ReferenceLine x={0} stroke="#cbd5e1"/><Tooltip formatter={value=>[bankMoney(String(value),group.currency),"Disponível"]} contentStyle={{borderRadius:12,fontSize:12}}/><Bar dataKey="amount" fill="#7c3aed" radius={[0,6,6,0]} maxBarSize={22}/></BarChart></ResponsiveContainer></div>}
          <div className="mt-3 space-y-2">{group.accounts.map(a=><div key={a.id} className="flex justify-between gap-3 text-[11px]"><span className="min-w-0 text-slate-500">{a.name}</span><span className="shrink-0 font-semibold text-slate-800">{bankMoney(a.rawAmount,group.currency)}</span></div>)}</div>{group.missing>0&&<p className="mt-3 text-xs text-amber-800">{group.missing} saldo(s) não informado(s), fora do total.</p>}</div>)}
      </article>
      <article className="min-w-0 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><OpenFinanceIcon name="card"/></span><div><h3 className="font-semibold text-slate-900">Crédito dos cartões</h3><p className="mt-1 text-[11px] text-slate-500">Utilizado e disponível, por linha de crédito</p></div></div>
        <div className="space-y-4">{cards.map(card=>{const lines=overview.limits.filter(l=>l.resource_id===card.id);return <div key={card.id} className="rounded-2xl border border-slate-100 bg-slate-50/50 p-4"><p className="text-sm font-semibold text-slate-800">{overview.connections.find(c=>c.id===card.connection_id)?.institution_name} · {bankResourceName(card.name)}</p>{!lines.length&&<p className="mt-3 text-xs text-slate-500">Limites não informados pelo banco.</p>}{lines.map(line=>{const used=ledgerAmount(line.used_amount==null?null:String(line.used_amount)),available=ledgerAmount(line.available_amount==null?null:String(line.available_amount));const denominator=used!==null&&available!==null?used+available:0;const percentage=used!==null&&used>=0&&available!==null&&available>=0&&denominator>0?Math.min(100,used/denominator*100):null;return <div key={line.id} className="mt-4"><p className="mb-2 text-[11px] text-slate-500">{line.line_name||"Linha do cartão"}{line.consolidation_type?` · ${line.consolidation_type}`:""}</p><div className="h-3 overflow-hidden rounded-full bg-slate-200" role="img" aria-label={percentage===null?"Uso do crédito sem proporção disponível":`${Math.round(percentage)}% utilizado`}><div className="h-full rounded-full bg-blue-500" style={{width:percentage===null?"0%":`${percentage}%`}}/></div><div className="mt-3 grid grid-cols-3 gap-2 text-[10px] text-slate-500"><div>Utilizado<p className="mt-1 break-words text-xs font-semibold text-slate-800">{bankMoney(line.used_amount,line.currency)}</p></div><div>Disponível<p className="mt-1 break-words text-xs font-semibold text-emerald-700">{bankMoney(line.available_amount,line.currency)}</p></div><div>Limite total<p className="mt-1 break-words text-xs font-semibold text-slate-800">{bankMoney(line.total_amount,line.currency)}</p></div></div>{percentage===null&&<p className="mt-2 text-[10px] text-slate-400">{denominator===0&&used===0&&available===0?"Banco informou limites zerados.":"Dados insuficientes para calcular o uso."}</p>}</div>;})}</div>;})}{!cards.length&&<p className="py-12 text-center text-sm text-slate-400">Nenhum cartão recebido nesta área.</p>}</div><p className="mt-4 text-[10px] leading-5 text-slate-400">Linhas podem compartilhar o mesmo limite e não são somadas. Crédito disponível não é saldo em conta.</p>
      </article>
    </div>
    <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-4"><h3 className="font-semibold text-slate-900">Gastos por origem</h3><p className="mt-1 text-xs text-slate-500">Conta, cartão, WhatsApp e plataforma · valores líquidos em reais</p></div><div className="grid items-center gap-5 sm:grid-cols-2">{expenses.length?<><div role="img" aria-label="Gastos e estornos por origem"><ResponsiveContainer width="100%" height={190}><BarChart data={expenses} layout="vertical" margin={{left:0,right:12,top:8,bottom:8}}><CartesianGrid horizontal={false} stroke="#f1f5f9"/><XAxis type="number" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis dataKey="name" type="category" width={100} tick={{fontSize:11}} axisLine={false} tickLine={false}/><ReferenceLine x={0} stroke="#cbd5e1"/><Bar dataKey="value" maxBarSize={24} radius={[0,6,6,0]}>{expenses.map((e,i)=><Cell key={e.name} fill={e.value<0?"#10b981":colors[i%colors.length]}/>)}</Bar><Tooltip formatter={value=>[bankMoney(String(value),"BRL"),"Gasto líquido"]} contentStyle={{borderRadius:12,fontSize:12}}/></BarChart></ResponsiveContainer></div><div className="space-y-4">{expenses.map((e,i)=><div key={e.name} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 text-slate-600"><span className="h-2.5 w-2.5 rounded-full" style={{background:e.value<0?"#10b981":colors[i%colors.length]}}/>{e.name}{e.value<0?" · ajustes/estornos":""}</span><strong className="text-slate-900">{bankMoney(String(e.value),"BRL")}</strong></div>)}</div></>:<p className="py-12 text-center text-sm text-slate-400">Nenhum gasto recebido neste período.</p>}</div><p className="mt-3 text-[10px] leading-5 text-slate-400">Estornos reduzem os gastos. Pagamentos de fatura e transferências identificadas ficam fora do resultado. Registros sinalizados como possível repetição ainda exigem conferência.</p></article>
    <p className="text-[11px] text-slate-500">Atualização automática · última importação concluída em {bankDate(data.report.last_successful_sync_at)} · histórico bancário pode estar incompleto{data.report.sync_pending?" · há dados sendo atualizados":""}</p>
  </section>;
}
