"use client";
import {useState} from "react";
import {bankDate,bankMoney,bankResourceName} from "@/lib/open-finance-display";
import type {BankFinancialData} from "@/lib/open-finance-report";
import OpenFinanceIcon from "./OpenFinanceIcon";
export default function OpenFinanceFinancial({mode,data}:{mode:"personal"|"business";data:BankFinancialData}) {
  const [error,setError]=useState(""),[asking,setAsking]=useState(false),[question,setQuestion]=useState(""),[answer,setAnswer]=useState("");
  async function ask(){if(asking)return;setAsking(true);setError("");try{const response=await fetch(`/api/open-finance/ask?mode=${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Tente novamente.");setAnswer(result.answer);}catch(e){setError(e instanceof Error?e.message:"Tente novamente.");}finally{setAsking(false);}}
  if(!data.overview.connections.length)return null;
  return <section aria-label="Faturas e consultas dos bancos" className="space-y-4 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7">
    <div><h2 className="text-lg font-semibold text-slate-900">Detalhes dos bancos</h2><p className="mt-1 text-xs text-slate-500">As movimentações já estão no extrato acima. Aqui você consulta faturas, limites e investimentos.</p></div>
      <details className="group rounded-2xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-5 py-4 text-sm font-semibold text-slate-900 [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><OpenFinanceIcon name="card" className="h-4 w-4 text-violet-600"/>Faturas recebidas<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-medium text-slate-500">{data.overview.bills.length}</span></span><span aria-hidden="true" className="text-slate-400 transition group-open:rotate-180">⌄</span></summary><div className="border-t border-slate-100 px-5 pb-5"><p className="mt-3 text-xs leading-5 text-slate-500">O vencimento da fatura e a data da compra são informações diferentes. O total da fatura não é somado às compras.</p>{data.overview.bills.map(b=><div key={b.id} className="mt-3 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-medium">{bankResourceName(data.overview.resources.find(r=>r.id===b.resource_id)?.name||"Cartão")} · vence em {bankDate(b.due_date)}</p><p className="mt-2">Total: {bankMoney(b.total_amount,b.currency)} · mínimo: {bankMoney(b.minimum_payment_amount,b.currency)}</p><p className="mt-1 text-xs text-slate-500">Situação de pagamento: {b.status==="unknown"?"não informada pelo banco":b.status}</p></div>)}{!data.overview.bills.length&&<p className="mt-4 text-sm text-slate-500">O banco ainda não enviou faturas.</p>}</div></details>
      <form onSubmit={e=>{e.preventDefault();void ask();}} className="rounded-2xl border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-700 text-white"><OpenFinanceIcon name="spark"/></span><div><label htmlFor="bank-question" className="text-sm font-semibold text-slate-900">Sua Zelo entende os números com você.</label><p className="mt-1 text-xs leading-5 text-slate-500">Consulte gastos, limites e investimentos a partir dos dados recebidos dos bancos.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{["Quanto gastei nos cartões mês passado?","Qual meu limite disponível?","Como estão meus investimentos?"].map(q=><button key={q} type="button" onClick={()=>setQuestion(q)} className="rounded-full border border-violet-100 bg-white px-3 py-1.5 text-[11px] text-violet-700 hover:bg-violet-50">{q}</button>)}</div><div className="mt-4 flex flex-wrap gap-2"><input id="bank-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} required placeholder="O que você quer saber sobre seus bancos?" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-violet-200"/><button disabled={asking} className="rounded-xl bg-violet-700 px-4 py-3 text-sm font-semibold text-white hover:bg-violet-800 disabled:opacity-50">{asking?"Consultando...":"Perguntar à Zelo"}</button></div>{answer&&<p role="status" className="mt-4 whitespace-pre-wrap rounded-xl border border-violet-100 bg-white p-4 text-sm leading-6 text-slate-700">{answer}</p>}</form>
      {data.overview.truncated&&<p className="text-xs text-amber-900">Há mais registros do que esta visão consegue mostrar. O resumo de contas e faturas está limitado.</p>}
      {error&&<p role="alert" className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900">{error}</p>}<p className="flex items-center gap-1.5 text-[11px] text-slate-500"><OpenFinanceIcon name="clock" className="h-3.5 w-3.5"/>Última atualização concluída: {bankDate(data.report.last_successful_sync_at)}</p>
  </section>;
}
