"use client";
import { useEffect, useState } from "react";
import type { BankInstitution } from "@/lib/open-finance-institutions";
import { BANK_CATEGORIES, matchesBank, type BankAuthorization } from "@/lib/open-finance-display";
const TERMS="https://drive.google.com/file/d/11H_jnnBRYSJcAgh9sgUCjPhXH2-7FoNj/view";
const PRIVACY="https://www.celcoin.com.br/wp-content/uploads/2026/07/2026_V6.0_NORMA_DE_PRIVACIDADE_EXTERNA.pdf";
const COMPLIANCE="https://www.celcoin.com.br/compliance-e-regulatorio/";
const PURPOSES=["Verificação antifraude e validação de identidade e cadastro","Agregação e gestão de dados pessoais","Avaliação de risco, inclusive de crédito","Avaliação de perfil e de padrões de consumo do usuário","Desenvolvimento, atualização, otimização e implementação de medidas de prevenção e segurança","Desenvolvimento de estudos, pesquisas, campanhas, serviços e produtos","Cumprimento de obrigações legais","Comunicação com o usuário","Proteção dos direitos do usuário"];
export function OpenFinancePurposes(){return <details><summary className="cursor-pointer font-semibold">Finalidade do Compartilhamento</summary><ul className="mt-2 list-disc space-y-1 pl-5">{PURPOSES.map(p=><li key={p}>{p}</li>)}</ul></details>;}
export function OpenFinanceAuthorization({authorization}:{authorization:BankAuthorization}){
  if(authorization.authorizationPending)return <p role="status" className="rounded-lg bg-amber-50 p-3 text-amber-900">Consentimento criado; a autorização ainda está indisponível enquanto conferimos o endereço <span className="font-semibold">{authorization.authorizationHost}</span>. Depois da conferência, use “Voltei do banco / verificar conexão” no histórico para continuar. Você ainda não autorizou o banco.</p>;
  if(authorization.authorizationExpired)return <p role="status" className="rounded-lg bg-amber-50 p-3 text-amber-900">O link de autorização venceu. A renovação desta conexão precisa ser preparada antes de continuar; nenhuma nova conexão foi criada automaticamente.</p>;
  if(authorization.authorizationUrl)return <a href={authorization.authorizationUrl} target="_blank" rel="noopener noreferrer" className="inline-block rounded-xl bg-indigo-700 px-4 py-2.5 font-semibold text-white">Ir para o banco</a>;
  return <p>O pedido está registrado. Confira o estado no histórico.</p>;
}
const DESCRIPTIONS:Record<string,string>={ACCOUNT:"Identificação da conta; saldos disponíveis, bloqueados e outros; cheque especial contratado e utilizado; detalhes das transações.",CREDIT_CARD_ACCOUNT:"Identificação, bandeira e informações do cartão; limites total, disponível, utilizado e por modalidade; estabelecimentos, datas e valores das transações; faturas, encargos e pagamentos.",INVESTMENTS:"Produto, remuneração e indexadores; emissão, aquisição, carência e vencimento; saldos bloqueado, bruto e líquido; quantidade e preço dos títulos; impostos, multa e mora; ISIN, classificação ANBIMA, classe e subclasse de renda fixa, renda variável, Tesouro e fundos.",CREDIT_OPERATIONS:"Contrato e documento da instituição consignante; contratação, liberação, valor e moeda; calendário de parcelas, periodicidade, primeiro e demais vencimentos e pagamentos; saldo devedor, prazos e prestações; juros, CET e amortização; tarifas com identificação, valor e cobrança; encargos e garantias."};
export default function OpenFinanceConnect({mode,contactEmail,onClose}:{mode:"personal"|"business";contactEmail?:string;onClose:()=>void}){
  const [step,setStep]=useState(0),[banks,setBanks]=useState<BankInstitution[]>([]),[query,setQuery]=useState(""),[bank,setBank]=useState<BankInstitution|null>(null),[cpf,setCpf]=useState(""),[cnpj,setCnpj]=useState(""),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[authorization,setAuthorization]=useState<BankAuthorization>({authorizationUrl:null});
  useEffect(()=>{const controller=new AbortController();void fetch(`/api/open-finance/institutions?mode=${mode}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("Não foi possível listar os bancos.");setBanks(await r.json());}).catch(e=>{if(e.name!=="AbortError")setError(e.message);});return()=>controller.abort();},[mode]);
  async function connect(event:React.FormEvent){
    event.preventDefault();if(!bank||!accepted)return;setBusy(true);setError("");
    try{const r=await fetch(`/api/open-finance/connect?mode=${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({institutionId:bank.id,cpf,...(mode==="business"?{cnpj}:{}),acceptedTerms:accepted,journeyVersion:"celcoin-2026-10"})});const body=await r.json();if(!r.ok)throw new Error(body.error||"Não foi possível conectar.");setAuthorization(body);setStep(3);}catch(e){setError(e instanceof Error?e.message:"Tente novamente.");}finally{setCpf("");setCnpj("");setBusy(false);}
  }
  return <div className="space-y-4 rounded-xl border border-indigo-200 bg-white p-5 text-sm text-slate-800">
    <div className="flex items-center justify-between gap-2"><h3 className="text-base font-bold">Conectar banco · {mode==="personal"?"Pessoal":"Empresa"}</h3><button type="button" disabled={busy} onClick={onClose} className="rounded-lg border px-3 py-2">Fechar</button></div>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}
    {step===0&&<><p>Traga as informações autorizadas dos seus bancos para a Zelo. Você escolhe a instituição e autoriza diretamente no banco, com a Celcoin.</p><p>Ao continuar, você declara que concorda com os <a className="underline text-indigo-800" href={TERMS} target="_blank" rel="noopener noreferrer">Termos de Uso</a> e que leu e compreendeu a <a className="underline text-indigo-800" href={PRIVACY} target="_blank" rel="noopener noreferrer">Norma de Privacidade Externa</a> da Celcoin, em conformidade com as diretrizes de <a className="underline text-indigo-800" href={COMPLIANCE} target="_blank" rel="noopener noreferrer">Compliance e Regulatório</a>.</p><button onClick={()=>setStep(1)} className="rounded-xl bg-indigo-700 px-4 py-2.5 font-semibold text-white">Continuar</button></>}
    {step===1&&<><h4 className="font-semibold">Selecione a conta de onde quer compartilhar seus dados</h4><label className="block">Buscar banco<input value={query} onChange={e=>setQuery(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"/></label><div className="max-h-72 space-y-2 overflow-y-auto">{banks.filter(b=>matchesBank(b,query)).map(b=><button key={b.id} disabled={b.status!=="OPERATIONAL"||b.is_outage} onClick={()=>{setBank(b);setStep(2);}} className="block w-full rounded-lg border border-slate-200 p-3 text-left font-medium hover:bg-indigo-50 disabled:text-slate-500">{b.name}{b.status!=="OPERATIONAL"||b.is_outage?" · Temporariamente indisponível":""}</button>)}</div></>}
    {step===2&&bank&&<form onSubmit={connect} className="space-y-4"><h4 className="font-semibold">Confira o compartilhamento com {bank.name}</h4>
      <label className="block">CPF {mode==="business"?"do representante":"do titular"}<input required autoComplete="off" inputMode="numeric" maxLength={18} value={cpf} onChange={e=>setCpf(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2"/></label>
      {mode==="business"&&<label className="block">CNPJ da empresa<input required autoComplete="off" inputMode="numeric" maxLength={22} value={cnpj} onChange={e=>setCnpj(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2"/></label>}
      <p>Contato cadastrado na Zelo: {contactEmail||"o e-mail da sua conta"}. Esse contato não é enviado à API bancária.</p>
      <div className="space-y-2"><h4 className="font-semibold">Categorias de dados compartilhadas</h4>{Object.entries(BANK_CATEGORIES).map(([key,label])=><details key={key}><summary className="cursor-pointer font-medium">{label}</summary><p className="mt-1">{DESCRIPTIONS[key]}</p></details>)}</div>
      <OpenFinancePurposes/><p><strong>Prazo:</strong> indeterminado — até você cancelar.</p>
      <p>Caso sejam criadas novas operações de Dados da conta, Cartão de crédito, Investimentos ou Crédito, os recursos serão automaticamente inclusos no compartilhamento de dados</p>
      <p>Ao clicar em Continuar, você autoriza a Celcoin Instituição de Pagamento Ltda. a acessar informações disponíveis no Open Finance de acordo com os <a className="underline text-indigo-800" href={TERMS} target="_blank" rel="noopener noreferrer">Termos de Uso</a> apresentados nas telas anteriores. Você poderá revogar o compartilhamento através do Portal.</p>
      <p>Você será redirecionado pela Celcoin com a segurança do Open Finance. A Celcoin abrirá a autorização em {bank.name}; você se autentica no banco e volta para a Celcoin. A Zelo nunca solicita sua senha bancária.</p>
      <label className="flex items-start gap-2"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required className="mt-1"/><span>Li as informações e autorizo este compartilhamento.</span></label>
      <div className="flex gap-2"><button type="button" disabled={busy} onClick={()=>setStep(1)} className="rounded-xl border px-4 py-2.5">Voltar</button><button type="submit" disabled={!accepted||busy} className="rounded-xl bg-indigo-700 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{busy?"Preparando...":"Continuar"}</button></div>
    </form>}
    {step===3&&<><h4 className="font-semibold">{authorization.authorizationUrl?"Autorize no seu banco":"Conexão preparada"}</h4>{authorization.authorizationUrl&&<p>A autorização abre em outra aba, com a segurança do Open Finance. Ao terminar, volte à Zelo e use “Voltei do banco / verificar conexão” no histórico abaixo.</p>}<OpenFinanceAuthorization authorization={authorization}/><button onClick={onClose} className="ml-2 rounded-xl border px-4 py-2.5">Voltar às contas</button></>}
  </div>;
}
