"use client";
import {useCallback,useState} from "react";
import {bankDate,bankMoney,bankResourceName} from "@/lib/open-finance-display";
import {BANK_HISTORY_NOTICE,BANK_TOTAL_LABELS,type BankFinancialData} from "@/lib/open-finance-report";
import {useBankUpdates} from "./useBankUpdates";
import OpenFinanceIcon from "./OpenFinanceIcon";
async function loadFinancial(mode:string,from:string,to:string,after?:string,signal?:AbortSignal):Promise<BankFinancialData|null> {
  const query=new URLSearchParams({mode,from,to});if(after)query.set("after",after);
  const response=await fetch(`/api/open-finance/report?${query}`,{cache:"no-store",signal});
  if(response.status===401||response.status===404)return null;
  const body=await response.json();if(!response.ok)throw new Error(body.error||"Não foi possível atualizar os bancos.");return body;
}
export default function OpenFinanceFinancial({mode,from,to}:{mode:"personal"|"business";from:string;to:string}) {
  const [paginationStarted,setPaginationStarted]=useState(false);
  const loader=useCallback((signal:AbortSignal)=>loadFinancial(mode,from,to,undefined,signal),[mode,from,to]);
  // Keep pages the user expanded. Resume live updates explicitly with a fresh first page.
  const {data,setData,error:updatesError}=useBankUpdates(loader,!paginationStarted);
  const [error,setError]=useState(""),[loadingMore,setLoadingMore]=useState(false),[asking,setAsking]=useState(false),[question,setQuestion]=useState(""),[answer,setAnswer]=useState("");
  async function more(){if(loadingMore||!data?.report.next)return;setPaginationStarted(true);setLoadingMore(true);setError("");try{const next=await loadFinancial(mode,from,to,data.report.next);if(next)setData({...next,report:{...next.report,movements:[...data.report.movements,...next.report.movements]}});}catch(e){setError(e instanceof Error?e.message:"Tente novamente.");setPaginationStarted(false);}finally{setLoadingMore(false);}}
  async function ask(){if(asking)return;setAsking(true);setError("");try{const response=await fetch(`/api/open-finance/ask?mode=${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Tente novamente.");setAnswer(result.answer);}catch(e){setError(e instanceof Error?e.message:"Tente novamente.");}finally{setAsking(false);}}
  if(!data)return (error||updatesError)?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error||updatesError}</p>:null;
  if(!data.overview.connections.length)return null;
  return <section aria-label="Financeiro dos bancos conectados" className="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-100 bg-gradient-to-r from-violet-50/80 via-white to-white px-5 py-6 sm:px-7"><div><p className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.16em] text-violet-700"><OpenFinanceIcon name="bank" className="h-4 w-4"/>Open Finance · {mode==="business"?"Empresa":"Pessoal"}</p><h2 className="text-2xl font-semibold tracking-tight text-slate-950">Seu dinheiro, em movimento.</h2><p className="mt-2 text-sm text-slate-500">Movimentações recebidas dos seus bancos · {bankDate(from)} a {bankDate(to)}</p></div><span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-[11px] font-medium text-slate-600"><OpenFinanceIcon name="shield" className="h-3.5 w-3.5"/>Autorização feita no banco</span></div>
    <div className="space-y-5 p-5 sm:p-7">
      {data.report.sync_pending&&<p role="status" className="flex items-start gap-2 rounded-xl border border-amber-100 bg-amber-50/60 px-4 py-3 text-xs leading-5 text-amber-900"><OpenFinanceIcon name="clock" className="mt-0.5 h-4 w-4 shrink-0"/>Há dados em atualização ou aguardando nova tentativa. O painel acompanha o que já foi recebido; confira a conexão em Contas.</p>}
      {!!data.report.missing_dates&&<p className="text-xs text-amber-900">{data.report.missing_dates} movimentação(ões) sem data não entram nos totais do período.</p>}
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.report.totals.filter(t=>t.kind!=="excluded").map(t=><article key={`${t.kind}-${t.currency}`} className={`min-w-0 rounded-2xl border p-5 ${t.kind==="credits"?"border-emerald-100 bg-emerald-50/50":"border-slate-200 bg-slate-50/50"}`}><div className="mb-5 flex items-start justify-between gap-2"><p className="text-xs font-medium leading-5 text-slate-600">{BANK_TOTAL_LABELS[t.kind]}</p><span className={`rounded-lg p-2 ${t.kind==="credits"?"bg-emerald-100 text-emerald-700":"bg-white text-violet-600 shadow-sm"}`}><OpenFinanceIcon name={t.kind==="credits"?"down":t.kind==="card_purchases"?"card":"up"} className="h-4 w-4"/></span></div><p className="break-words text-2xl font-semibold tracking-tight text-slate-950">{bankMoney(t.amount,t.currency)}</p><p className="mt-2 text-[11px] text-slate-500">{t.count} movimentação(ões){t.missing_amounts?` · ${t.missing_amounts} sem valor informado`:""}</p></article>)}</div>
      <details className="rounded-xl bg-slate-50 px-4 py-3 text-xs text-slate-600"><summary className="cursor-pointer font-medium">Dados recebidos · histórico pode estar incompleto · lançamentos manuais separados</summary><p className="mt-3 leading-6">{BANK_HISTORY_NOTICE} Estes valores ficam separados dos lançamentos manuais abaixo.</p></details>
      <div className="overflow-hidden rounded-2xl border border-slate-200"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h3 className="text-sm font-semibold text-slate-900">Movimentações dos bancos</h3><p className="mt-1 text-[11px] text-slate-500">{data.report.movements.length} registros exibidos neste período</p></div>{paginationStarted?<button disabled={loadingMore} onClick={()=>{if(!loadingMore)setPaginationStarted(false);}} className="rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600 disabled:opacity-50">Atualizar lista</button>:<span className="flex items-center gap-1.5 text-[11px] text-slate-500"><span className={`h-1.5 w-1.5 rounded-full ${updatesError?"bg-amber-500":"bg-emerald-500"}`}/>Atualização automática</span>}</div>
        <div className="divide-y divide-slate-100">{data.report.movements.map(m=><article key={m.id} className="flex items-start gap-3 px-4 py-4 transition hover:bg-slate-50 sm:px-5"><span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${m.direction==="credit"?"bg-emerald-50 text-emerald-600":"bg-violet-50 text-violet-600"}`}><OpenFinanceIcon name={m.direction==="credit"?"down":"up"} className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="break-words text-sm font-medium text-slate-900">{m.description}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{m.institution_name} · {bankResourceName(m.resource_name)} · {bankDate(m.date)}</p><p className="mt-1 text-[10px] text-slate-500">{BANK_TOTAL_LABELS[m.kind]}</p>{m.installment_number&&<p className="mt-1 text-[11px] text-slate-500">Parcela {m.installment_number}{m.installment_count?` de ${m.installment_count}`:""}{m.bill_month?` · competência ${m.bill_month.slice(5,7)}/${m.bill_month.slice(0,4)}`:""}</p>}</div><div className="max-w-[42%] shrink-0 text-right"><p className={`break-words text-sm font-semibold tabular-nums ${m.direction==="credit"?"text-emerald-700":"text-slate-900"}`}>{bankMoney(m.amount,m.currency)}</p><p className="mt-1 text-[10px] text-slate-500">{m.direction==="debit"?"Saída":m.direction==="credit"?"Entrada":"Direção não informada"}</p></div></article>)}</div>
        {!data.report.movements.length&&<p className="px-5 py-8 text-center text-sm text-slate-500">Nenhuma movimentação recebida para este período.</p>}
        {data.report.next&&<div className="border-t border-slate-100 p-4 text-center"><button disabled={loadingMore} onClick={()=>void more()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50">{loadingMore?"Carregando...":"Ver mais movimentações"}</button></div>}
      </div>
      <details className="group rounded-2xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-5 py-4 text-sm font-semibold text-slate-900 [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><OpenFinanceIcon name="card" className="h-4 w-4 text-violet-600"/>Faturas recebidas<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-medium text-slate-500">{data.overview.bills.length}</span></span><span aria-hidden="true" className="text-slate-400 transition group-open:rotate-180">⌄</span></summary><div className="border-t border-slate-100 px-5 pb-5"><p className="mt-3 text-xs leading-5 text-slate-500">O vencimento da fatura e a data da compra são informações diferentes. O total da fatura não é somado às compras.</p>{data.overview.bills.map(b=><div key={b.id} className="mt-3 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-medium">{bankResourceName(data.overview.resources.find(r=>r.id===b.resource_id)?.name||"Cartão")} · vence em {bankDate(b.due_date)}</p><p className="mt-2">Total: {bankMoney(b.total_amount,b.currency)} · mínimo: {bankMoney(b.minimum_payment_amount,b.currency)}</p><p className="mt-1 text-xs text-slate-500">Situação de pagamento: {b.status==="unknown"?"não informada pelo banco":b.status}</p></div>)}{!data.overview.bills.length&&<p className="mt-4 text-sm text-slate-500">O banco ainda não enviou faturas.</p>}</div></details>
      <form onSubmit={e=>{e.preventDefault();void ask();}} className="rounded-2xl border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-700 text-white"><OpenFinanceIcon name="spark"/></span><div><label htmlFor="bank-question" className="text-sm font-semibold text-slate-900">Sua Zelo entende os números com você.</label><p className="mt-1 text-xs leading-5 text-slate-500">Consulte gastos, limites e investimentos a partir dos dados recebidos dos bancos.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{["Quanto gastei nos cartões mês passado?","Qual meu limite disponível?","Como estão meus investimentos?"].map(q=><button key={q} type="button" onClick={()=>setQuestion(q)} className="rounded-full border border-violet-100 bg-white px-3 py-1.5 text-[11px] text-violet-700 hover:bg-violet-50">{q}</button>)}</div><div className="mt-4 flex flex-wrap gap-2"><input id="bank-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} required placeholder="O que você quer saber sobre seus bancos?" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-violet-200"/><button disabled={asking} className="rounded-xl bg-violet-700 px-4 py-3 text-sm font-semibold text-white hover:bg-violet-800 disabled:opacity-50">{asking?"Consultando...":"Perguntar à Zelo"}</button></div>{answer&&<p role="status" className="mt-4 whitespace-pre-wrap rounded-xl border border-violet-100 bg-white p-4 text-sm leading-6 text-slate-700">{answer}</p>}</form>
      {data.overview.truncated&&<p className="text-xs text-amber-900">Há mais registros do que esta visão consegue mostrar. O resumo de contas e faturas está limitado.</p>}
      {(error||updatesError)&&<p role="alert" className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900">{error||updatesError}</p>}<p className="flex items-center gap-1.5 text-[11px] text-slate-500"><OpenFinanceIcon name="clock" className="h-3.5 w-3.5"/>Última atualização concluída: {bankDate(data.report.last_successful_sync_at)}</p>
    </div>
  </section>;
}
